<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createAddress, deleteAddress, getAddresses, updateAddress } from '@/api/user'
const list = ref([]); const dialog = ref(false); const editingId = ref(null); const formRef = ref(); const form = reactive({ receiver: '', phone: '', province: '', city: '', district: '', detail: '', is_default: 0 })
const rules = { receiver: [{ required: true, message: '请输入收货人', trigger: 'blur' }], phone: [{ required: true, message: '请输入手机号', trigger: 'blur' }], province: [{ required: true, message: '请输入省份', trigger: 'blur' }], city: [{ required: true, message: '请输入城市', trigger: 'blur' }], district: [{ required: true, message: '请输入区县', trigger: 'blur' }], detail: [{ required: true, message: '请输入详细地址', trigger: 'blur' }] }
async function load() { list.value = await getAddresses() }
function open(item = null) { editingId.value = item?.id || null; Object.assign(form, item ? { ...item } : { receiver: '', phone: '', province: '', city: '', district: '', detail: '', is_default: !list.value.length ? 1 : 0 }); dialog.value = true }
async function save() { await formRef.value.validate(); if (editingId.value) await updateAddress(editingId.value, form); else await createAddress(form); ElMessage.success('地址已保存'); dialog.value = false; await load() }
async function remove(id) { await ElMessageBox.confirm('删除后无法恢复，确认删除此地址？', '删除地址', { type: 'warning' }); await deleteAddress(id); ElMessage.success('地址已删除'); await load() }
onMounted(load)
</script>

<template><section class="content-card panel"><div class="panel-title"><div><h1>收货地址</h1><p>管理下单时使用的收货信息</p></div><el-button type="primary" @click="open()">新增地址</el-button></div><div v-if="list.length" class="address-grid"><article v-for="item in list" :key="item.id" class="address-card" :class="{ default: item.is_default }"><div><b>{{ item.receiver }}</b><span>{{ item.phone }}</span><el-tag v-if="item.is_default" size="small" type="danger">默认</el-tag></div><p>{{ item.province }}{{ item.city }}{{ item.district }}{{ item.detail }}</p><div><el-button link type="primary" @click="open(item)">编辑</el-button><el-button link type="danger" @click="remove(item.id)">删除</el-button></div></article></div><el-empty v-else description="暂无收货地址"><el-button type="primary" @click="open()">新增地址</el-button></el-empty></section><el-dialog v-model="dialog" :title="editingId ? '编辑收货地址' : '新增收货地址'" width="600px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-width="5rem"><el-form-item label="收货人" prop="receiver"><el-input v-model="form.receiver" /></el-form-item><el-form-item label="手机号" prop="phone"><el-input v-model="form.phone" /></el-form-item><el-form-item label="省份" prop="province"><el-input v-model="form.province" placeholder="如：浙江省" /></el-form-item><el-form-item label="城市" prop="city"><el-input v-model="form.city" /></el-form-item><el-form-item label="区县" prop="district"><el-input v-model="form.district" /></el-form-item><el-form-item label="详细地址" prop="detail"><el-input v-model="form.detail" type="textarea" /></el-form-item><el-form-item label="设为默认"><el-switch v-model="form.is_default" :active-value="1" :inactive-value="0" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" @click="save">保存地址</el-button></template></el-dialog></template>

<style scoped>
.panel { padding: clamp(1.2rem, 3vw, 2rem); }.panel-title { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding-bottom: 1.25rem; border-bottom: 1px solid #edf0f4; }.panel-title h1 { margin: 0; font-size: 1.4rem; letter-spacing: -.05em; }.panel-title p { margin: .35rem 0 0; color: #98a2b3; font-size: .85rem; }.panel-title :deep(.el-button--primary), :deep(.el-button--primary) { background: #ec552f; border-color: #ec552f; }.address-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: .85rem; padding-top: 1.25rem; }.address-card { padding: 1rem; border: 1px solid #e4e7ec; border-radius: .65rem; }.address-card.default { border-color: #f3ae93; background: #fffaf8; }.address-card > div:first-child { display: flex; align-items: center; gap: .6rem; }.address-card span { color: #667085; font-size: .85rem; }.address-card p { min-height: 2.6rem; color: #475467; font-size: .85rem; line-height: 1.55; }
@media (max-width: 600px) { .address-grid { grid-template-columns: 1fr; } }
</style>
