<script setup>
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getAdminOrders, shipOrder } from '@/api/admin'

const list = ref([]); const total = ref(0); const page = ref(1); const status = ref(''); const loading = ref(false)
const statuses = [{ label: '全部订单', value: '' }, { label: '待付款', value: 'pending' }, { label: '待发货', value: 'paid' }, { label: '待收货', value: 'shipped' }, { label: '已完成', value: 'completed' }, { label: '已取消', value: 'cancelled' }]
async function load() { loading.value = true; try { const data = await getAdminOrders({ page: page.value, pageSize: 10, status: status.value || undefined }); list.value = data.list; total.value = data.total } finally { loading.value = false } }
async function ship(order) { await ElMessageBox.confirm(`确认向 ${order.username} 模拟发货吗？订单将进入“待收货”。`, '模拟发货', { type: 'info', confirmButtonText: '确认发货' }); await shipOrder(order.id); ElMessage.success('已模拟发货'); await load() }
function changeStatus() { page.value = 1; load() }
onMounted(load)
</script>

<template><section class="admin-content"><div class="admin-title"><div><span>ORDER FULFILLMENT</span><h1>订单发货</h1><p>待付款订单不可发货；仅已付款订单可以模拟发货。</p></div></div><el-radio-group v-model="status" class="status-filter" @change="changeStatus"><el-radio-button v-for="item in statuses" :key="item.value" :label="item.value">{{ item.label }}</el-radio-button></el-radio-group><el-table v-loading="loading" :data="list" class="orders-table"><el-table-column label="订单 / 用户" min-width="190"><template #default="{ row }"><div class="order-identity"><b>{{ row.order_no }}</b><small>{{ row.username }} · {{ row.email }}</small></div></template></el-table-column><el-table-column label="商品" min-width="210"><template #default="{ row }"><div class="order-products"><span v-for="item in row.items" :key="item.id">{{ item.goods_name }} × {{ item.quantity }}</span></div></template></el-table-column><el-table-column label="收货地址" min-width="180"><template #default="{ row }"><span v-if="row.receiver">{{ row.receiver }} {{ row.phone }}<br />{{ row.province }}{{ row.city }}{{ row.district }}{{ row.detail }}</span><span v-else class="muted">未填写地址</span></template></el-table-column><el-table-column label="金额" width="100"><template #default="{ row }">¥{{ Number(row.total_price).toFixed(2) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'cancelled' ? 'info' : row.status === 'pending' ? 'danger' : row.status === 'paid' ? 'warning' : 'success'">{{ row.status_text }}</el-tag></template></el-table-column><el-table-column label="下单时间" width="165"><template #default="{ row }">{{ new Date(row.created_at).toLocaleString('zh-CN', { hour12: false }) }}</template></el-table-column><el-table-column label="操作" width="110" fixed="right"><template #default="{ row }"><el-button v-if="row.status === 'paid'" type="primary" link @click="ship(row)">模拟发货</el-button><span v-else class="muted">—</span></template></el-table-column></el-table><el-empty v-if="!loading && !list.length" description="暂无相关订单" /><div class="admin-pagination"><el-pagination background layout="prev, pager, next" :current-page="page" :page-size="10" :total="total" @current-change="page = $event; load()" /></div></section></template>

<style scoped>
.admin-content { padding: clamp(1.2rem, 3vw, 2rem); }.admin-title > div > span { color: #ec6a42; font-size: .65rem; font-weight: 800; letter-spacing: .14em; }.admin-title h1 { margin: .25rem 0; font-size: 1.55rem; letter-spacing: -.05em; }.admin-title p { margin: 0; color: #98a2b3; font-size: .85rem; }.status-filter { display: flex; flex-wrap: wrap; gap: .35rem; margin: 1.5rem 0 1rem; }.status-filter :deep(.el-radio-button__inner) { border: 1px solid #d0d5dd !important; border-radius: .35rem !important; box-shadow: none !important; }.orders-table { width: 100%; }.order-identity, .order-products { display: grid; gap: .28rem; }.order-identity b { color: #344054; font-size: .83rem; }.order-identity small, .order-products span { color: #667085; font-size: .78rem; line-height: 1.45; }.admin-pagination { display: flex; justify-content: flex-end; padding-top: 1.2rem; }
@media (max-width: 580px) { .admin-content { padding: 1rem; }.admin-pagination { justify-content: center; } }
</style>
