<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Delete, Location } from '@element-plus/icons-vue'
import { getAddresses } from '@/api/user'
import { useCartStore } from '@/stores/cartStore'
import { useOrderStore } from '@/stores/orderStore'

const router = useRouter(); const cartStore = useCartStore(); const orderStore = useOrderStore()
const selectedIds = ref([]); const addressDialog = ref(false); const addresses = ref([]); const addressId = ref(null); const submitting = ref(false)
const selectedItems = computed(() => cartStore.items.filter(item => selectedIds.value.includes(item.id) && item.status))
const total = computed(() => selectedItems.value.reduce((sum, item) => sum + Number(item.subtotal), 0))
const allChecked = computed({ get: () => cartStore.items.filter(i => i.status).length > 0 && selectedItems.value.length === cartStore.items.filter(i => i.status).length, set: (value) => { selectedIds.value = value ? cartStore.items.filter(i => i.status).map(i => i.id) : [] } })
async function load() { await cartStore.fetchCart(); selectedIds.value = cartStore.items.filter(item => item.status).map(item => item.id) }
async function quantityChange(item, value) { try { await cartStore.updateCart(item.id, value) } catch { await load() } }
async function checkout() { if (!selectedItems.value.length) return ElMessage.warning('请先选择需要结算的商品'); addresses.value = await getAddresses(); addressId.value = addresses.value.find(item => item.is_default)?.id || addresses.value[0]?.id || null; addressDialog.value = true }
async function submitOrder() { if (!addressId.value) return ElMessage.warning('请先添加并选择收货地址'); submitting.value = true; try { const order = await orderStore.createOrder({ address_id: addressId.value, items: selectedItems.value.map(item => ({ goods_id: item.goods_id, quantity: item.quantity, cart_id: item.id })) }); ElMessage.success('订单创建成功'); addressDialog.value = false; await load(); router.push(`/user/orders/${order.id}`) } finally { submitting.value = false } }
watch(() => cartStore.items.length, () => { selectedIds.value = selectedIds.value.filter(id => cartStore.items.some(item => item.id === id)) })
onMounted(load)
</script>

<template>
  <div class="page-shell"><div class="page-title"><span class="eyebrow orange">MY CART</span><h1>购物车</h1><p>确认好每一件想带走的好物</p></div><section v-loading="cartStore.loading" class="content-card cart-card"><template v-if="cartStore.items.length"><div class="cart-head"><el-checkbox v-model="allChecked">全选</el-checkbox><span>商品信息</span><span>单价</span><span>数量</span><span>小计</span><span>操作</span></div><article v-for="item in cartStore.items" :key="item.id" class="cart-item" :class="{ disabled: !item.status }"><el-checkbox v-model="selectedIds" :label="item.id" :disabled="!item.status"><span class="sr-only">选择{{ item.name }}</span></el-checkbox><router-link :to="`/detail/${item.goods_id}`" class="cart-product"><img :src="item.image" :alt="item.name" /><span><b>{{ item.name }}</b><small v-if="!item.status">商品已下架</small></span></router-link><span class="unit-price">¥{{ Number(item.price).toFixed(2) }}</span><el-input-number :model-value="item.quantity" :min="1" :max="item.stock" :disabled="!item.status" size="small" @change="quantityChange(item, $event)" /><span class="subtotal">¥{{ Number(item.subtotal).toFixed(2) }}</span><el-button circle text type="danger" aria-label="删除商品" @click="cartStore.removeCart(item.id)"><el-icon><Delete /></el-icon></el-button></article><div class="cart-summary"><el-checkbox v-model="allChecked">全选</el-checkbox><span>已选 {{ selectedItems.length }} 件商品</span><div class="summary-price">合计 <strong>¥{{ total.toFixed(2) }}</strong><el-button type="primary" size="large" @click="checkout">去结算</el-button></div></div></template><el-empty v-else description="购物车还是空的"><el-button type="primary" @click="router.push('/goods')">去挑选商品</el-button></el-empty></section></div>
  <el-dialog v-model="addressDialog" title="确认收货地址" width="620px"><div v-if="addresses.length" class="address-list"><label v-for="address in addresses" :key="address.id" class="address-choice" :class="{ selected: addressId === address.id }"><el-radio v-model="addressId" :value="address.id"><b>{{ address.receiver }}</b> {{ address.phone }}<p>{{ address.province }}{{ address.city }}{{ address.district }}{{ address.detail }}</p></el-radio></label></div><el-empty v-else description="还没有收货地址"><el-button type="primary" @click="addressDialog = false; router.push('/user/address')"><el-icon><Location /></el-icon>去添加地址</el-button></el-empty><template #footer><el-button @click="addressDialog = false">取消</el-button><el-button type="primary" :loading="submitting" :disabled="!addresses.length" @click="submitOrder">提交订单 ¥{{ total.toFixed(2) }}</el-button></template></el-dialog>
</template>

<style scoped>
.page-title { margin-bottom: 1.1rem; }.eyebrow { display: block; margin-bottom: .3rem; font-size: .7rem; font-weight: 800; letter-spacing: .14em; }.orange { color: #ec6a42; }.page-title h1 { margin: 0; font-size: 2rem; letter-spacing: -.06em; }.page-title p { margin: .4rem 0 0; color: #98a2b3; }.cart-card { overflow: hidden; }.cart-head, .cart-item { display: grid; grid-template-columns: 2rem minmax(14rem, 1fr) 7rem 8rem 7rem 3rem; align-items: center; gap: 1rem; padding: 1rem 1.25rem; }.cart-head { background: #f9fafb; color: #667085; font-size: .82rem; }.cart-item { border-top: 1px solid #edf0f4; }.cart-item.disabled { opacity: .55; background: #fafafa; }.cart-product { display: flex; align-items: center; gap: .8rem; min-width: 0; }.cart-product img { width: 4.5rem; height: 4.5rem; border-radius: .55rem; object-fit: cover; }.cart-product span { display: grid; gap: .3rem; min-width: 0; }.cart-product b { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.cart-product small { color: #d92d20; }.unit-price { color: #475467; }.subtotal { color: #e64545; font-weight: 700; }.cart-summary { display: flex; align-items: center; gap: 1rem; padding: 1rem 1.25rem; border-top: 1px solid #edf0f4; color: #667085; }.summary-price { display: flex; align-items: center; gap: 1rem; margin-left: auto; }.summary-price strong { color: #e64545; font-size: 1.4rem; }.summary-price :deep(.el-button) { min-width: 7rem; background: #ec552f; border-color: #ec552f; }.address-list { display: grid; gap: .75rem; }.address-choice { display: block; padding: .85rem 1rem; border: 1px solid #e4e7ec; border-radius: .6rem; cursor: pointer; }.address-choice.selected { border-color: #ec552f; background: #fff7f4; }.address-choice p { margin: .4rem 0 0 1.5rem; color: #667085; font-size: .85rem; line-height: 1.55; }.sr-only { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0, 0, 0, 0); }
@media (max-width: 720px) { .cart-head { display: none; }.cart-item { grid-template-columns: 1.5rem minmax(0, 1fr) 2.4rem; gap: .6rem; }.cart-product { grid-column: 2; }.unit-price { grid-column: 2; grid-row: 2; margin-left: 5.3rem; }.cart-item :deep(.el-input-number) { grid-column: 2; grid-row: 3; margin-left: 5.3rem; }.subtotal { grid-column: 2; grid-row: 4; margin-left: 5.3rem; }.cart-item > .el-button { grid-column: 3; grid-row: 1; }.cart-summary { flex-wrap: wrap; }.summary-price { width: 100%; margin-left: 0; justify-content: flex-end; } }
</style>
