<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { cancelOrder, completeOrder } from '@/api/order'
import PaymentDialog from '@/components/PaymentDialog.vue'
import { useOrderStore } from '@/stores/orderStore'
const route = useRoute(); const router = useRouter(); const orderStore = useOrderStore(); const order = computed(() => orderStore.currentOrder); const paymentVisible = ref(false)
const progressIndex = computed(() => ({ pending: 0, paid: 1, shipped: 2, completed: 3 }[order.value?.status] ?? -1))
async function load() { try { await orderStore.fetchOrderDetail(route.params.id) } catch { router.replace('/user/orders') } }
async function cancel() { await ElMessageBox.confirm('确认取消这笔订单吗？', '取消订单', { type: 'warning' }); await cancelOrder(order.value.id); ElMessage.success('订单已取消'); await load() }
async function complete() { await ElMessageBox.confirm('确认已经收到商品吗？确认后订单将完成。', '确认收货', { type: 'success', confirmButtonText: '确认收货' }); await completeOrder(order.value.id); ElMessage.success('已确认收货'); await load() }
watch(() => route.params.id, load); onMounted(load)
</script>

<template><section v-if="order" class="content-card panel"><div class="detail-top"><div><el-button link @click="router.push('/user/orders')">← 返回订单列表</el-button><h1>订单详情</h1><p>订单号：{{ order.order_no }}</p></div><el-tag size="large" :type="order.status === 'cancelled' ? 'info' : order.status === 'pending' ? 'danger' : 'success'">{{ order.status_text }}</el-tag></div><div class="order-progress"><div v-for="(step, index) in ['提交订单', '待发货', '待收货', '订单完成']" :key="step" class="progress-step" :class="{ active: progressIndex >= index }"><i></i><span>{{ step }}</span></div></div><section class="detail-section"><h3>收货信息</h3><p v-if="order.receiver"><b>{{ order.receiver }}</b> {{ order.phone }}<br />{{ order.province }}{{ order.city }}{{ order.district }}{{ order.detail }}</p><p v-else class="muted">该订单未填写收货地址</p></section><section class="detail-section"><h3>商品清单</h3><article v-for="item in order.items" :key="item.id" class="detail-item"><img :src="item.goods_image" :alt="item.goods_name" /><div><b>{{ item.goods_name }}</b><p>下单单价 ¥{{ Number(item.price).toFixed(2) }} × {{ item.quantity }}</p></div><strong>¥{{ Number(item.subtotal).toFixed(2) }}</strong></article></section><section v-if="order.payment_last4" class="detail-section payment-receipt"><h3>支付信息</h3><p><b>{{ order.payment_brand }}</b> 信用卡 ···· {{ order.payment_last4 }}<br /><span v-if="order.paid_at">支付时间：{{ new Date(order.paid_at).toLocaleString('zh-CN', { hour12: false }) }}</span></p></section><div class="total-line">订单总额 <strong>¥{{ Number(order.total_price).toFixed(2) }}</strong></div><div class="detail-actions"><template v-if="order.status === 'pending'"><el-button @click="cancel">取消订单</el-button><el-button type="primary" @click="paymentVisible = true">去支付</el-button></template><el-button v-else-if="order.status === 'shipped'" type="primary" @click="complete">确认收货</el-button><span v-else-if="order.status === 'paid'" class="muted">已付款，等待商家发货</span></div></section><div v-else class="content-card loading-detail" v-loading="true"></div><PaymentDialog v-model="paymentVisible" :order="order" @paid="load" /></template>

<style scoped>
.panel { padding: clamp(1.2rem, 3vw, 2rem); }.detail-top { display: flex; align-items: flex-start; justify-content: space-between; gap: 1rem; }.detail-top h1 { margin: .25rem 0; font-size: 1.5rem; letter-spacing: -.05em; }.detail-top p { margin: 0; color: #98a2b3; font-size: .8rem; }.order-progress { display: grid; grid-template-columns: repeat(4, 1fr); margin: 2rem 0; }.progress-step { position: relative; display: grid; justify-items: center; gap: .45rem; color: #98a2b3; font-size: .78rem; }.progress-step::before { position: absolute; top: .42rem; left: -50%; width: 100%; height: .15rem; background: #e4e7ec; content: ''; }.progress-step:first-child::before { display: none; }.progress-step i { z-index: 1; width: 1rem; height: 1rem; border: .2rem solid #e4e7ec; border-radius: 50%; background: #fff; }.progress-step.active i { border-color: #ec552f; }.progress-step.active::before { background: #f4b29d; }.detail-section { padding: 1rem 0; border-top: 1px solid #edf0f4; }.detail-section h3 { margin: 0 0 .7rem; font-size: 1rem; }.detail-section > p { margin: 0; color: #667085; line-height: 1.7; font-size: .9rem; }.payment-receipt b { color: #243b78; }.detail-item { display: flex; align-items: center; gap: .8rem; padding: .65rem 0; }.detail-item img { width: 4rem; height: 4rem; border-radius: .5rem; object-fit: cover; }.detail-item div { flex: 1; }.detail-item p { margin: .35rem 0 0; color: #98a2b3; font-size: .8rem; }.detail-item strong { color: #475467; }.total-line { padding: 1rem 0; border-top: 1px solid #edf0f4; text-align: right; color: #667085; }.total-line strong { margin-left: .6rem; color: #e64545; font-size: 1.5rem; }.detail-actions { display: flex; justify-content: flex-end; gap: .7rem; }.detail-actions :deep(.el-button--primary) { background: #ec552f; border-color: #ec552f; }.loading-detail { min-height: 20rem; }
</style>
