<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { cancelOrder, completeOrder } from '@/api/order'
import PaymentDialog from '@/components/PaymentDialog.vue'
import { useOrderStore } from '@/stores/orderStore'
const router = useRouter(); const orderStore = useOrderStore(); const status = ref(''); const paymentVisible = ref(false); const paymentOrder = ref(null)
const statuses = [{ label: '全部订单', value: '' }, { label: '待付款', value: 'pending' }, { label: '待发货', value: 'paid' }, { label: '待收货', value: 'shipped' }, { label: '已完成', value: 'completed' }, { label: '已取消', value: 'cancelled' }]
const load = () => orderStore.fetchOrders(status.value ? { status: status.value } : {})
async function cancel(id) { await ElMessageBox.confirm('确认取消这笔订单吗？库存将自动恢复。', '取消订单', { type: 'warning' }); await cancelOrder(id); ElMessage.success('订单已取消'); await load() }
function openPayment(order) { paymentOrder.value = order; paymentVisible.value = true }
async function complete(id) { await ElMessageBox.confirm('确认已经收到商品吗？确认后订单将完成。', '确认收货', { type: 'success', confirmButtonText: '确认收货' }); await completeOrder(id); ElMessage.success('已确认收货'); await load() }
onMounted(load)
</script>

<template><section class="content-card panel"><div class="panel-title"><div><h1>我的订单</h1><p>查看每一笔消费记录</p></div></div><el-tabs v-model="status" @tab-change="load"><el-tab-pane v-for="item in statuses" :key="item.value" :label="item.label" :name="item.value" /></el-tabs><div v-loading="orderStore.loading"><article v-for="order in orderStore.list" :key="order.id" class="order-card"><div class="order-meta"><span>订单号：{{ order.order_no }}</span><span>{{ new Date(order.created_at).toLocaleString('zh-CN', { hour12: false }) }}</span><el-tag :type="order.status === 'cancelled' ? 'info' : order.status === 'pending' ? 'danger' : 'success'">{{ order.status_text }}</el-tag></div><div v-for="item in order.items" :key="item.id" class="order-item"><img :src="item.goods_image" :alt="item.goods_name" /><div><b>{{ item.goods_name }}</b><p>¥{{ Number(item.price).toFixed(2) }} × {{ item.quantity }}</p></div><strong>¥{{ Number(item.subtotal).toFixed(2) }}</strong></div><div class="order-footer"><span>共 {{ order.items.reduce((sum, item) => sum + item.quantity, 0) }} 件商品，合计 <b>¥{{ Number(order.total_price).toFixed(2) }}</b></span><div><el-button v-if="order.status === 'pending'" @click="cancel(order.id)">取消订单</el-button><el-button v-if="order.status === 'pending'" type="primary" @click="openPayment(order)">去支付</el-button><el-button v-if="order.status === 'shipped'" type="primary" @click="complete(order.id)">确认收货</el-button><el-button v-if="order.status === 'paid'" disabled>等待发货</el-button><el-button plain @click="router.push(`/user/orders/${order.id}`)">订单详情</el-button></div></div></article><el-empty v-if="!orderStore.loading && !orderStore.list.length" description="暂无相关订单"><el-button type="primary" @click="router.push('/goods')">去逛商品</el-button></el-empty></div></section><PaymentDialog v-model="paymentVisible" :order="paymentOrder" @paid="load" /></template>

<style scoped>
.panel { padding: clamp(1.2rem, 3vw, 2rem); }.panel-title { padding-bottom: .6rem; }.panel-title h1 { margin: 0; font-size: 1.4rem; letter-spacing: -.05em; }.panel-title p { margin: .35rem 0 0; color: #98a2b3; font-size: .85rem; }.order-card { overflow: hidden; margin-bottom: 1rem; border: 1px solid #e4e7ec; border-radius: .7rem; }.order-meta { display: flex; align-items: center; gap: 1rem; padding: .65rem 1rem; background: #f9fafb; color: #667085; font-size: .78rem; }.order-meta .el-tag { margin-left: auto; }.order-item { display: flex; align-items: center; gap: .8rem; padding: .8rem 1rem; }.order-item img { width: 3.7rem; height: 3.7rem; border-radius: .45rem; object-fit: cover; }.order-item div { flex: 1; min-width: 0; }.order-item b { display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.order-item p { margin: .35rem 0 0; color: #98a2b3; font-size: .8rem; }.order-item strong { color: #475467; }.order-footer { display: flex; align-items: center; justify-content: space-between; gap: 1rem; padding: .8rem 1rem; border-top: 1px solid #edf0f4; color: #667085; font-size: .85rem; }.order-footer b { color: #e64545; font-size: 1.05rem; }.order-footer :deep(.el-button--primary) { background: #ec552f; border-color: #ec552f; }
@media (max-width: 580px) { .order-meta { flex-wrap: wrap; gap: .35rem .7rem; }.order-meta .el-tag { margin-left: 0; }.order-footer { align-items: flex-end; flex-direction: column; } }
</style>
